apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: web-servers
spec:
  generators:
  - list:
      elements:
      - appName: nginx
        namespace: new
        path: nginx/                    # Points to nginx/ folder
      - appName: apache
        namespace: new2
        path: apache/                  # Points to apache/ folder
  template:
    metadata:
      name: '{{appName}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/sanket-aws-devops/gitops-manifests.git  # YOUR actual repo
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
