apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-site
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sanket-aws-devops/gitops-manifests.git
    targetRevision: HEAD
    path: k8s/
  destination:
    server: https://kubernetes.default.svc  # ‚Üê FIXED: Local cluster
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
