apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-site
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sanket2494/gitops-manifests.git
    targetRevision: HEAD
    path: k8s/  # Points to folder with deployment.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: web
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
