apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-site
  namespace: web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-site
  template:
    metadata:
      labels:
        app: nginx-site
    spec:
      containers:
      - name: nginx
        image: sanket2494/nginx-site:latest  # Your image!
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-site
  namespace: web
spec:
  type: NodePort
  selector:
    app: nginx-site
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
