apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-my-cluster
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sanket-aws-devops/gitops-manifests.git
    targetRevision: HEAD
    path: k8s  # Path to your deployment.yaml
  destination:
    name: vm2-cluster #'https://192.168.58.2:8443'  # From $SERVER
    namespace: web2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
